// The coffee log. One tuple per bag:
// [name, roaster, roast, origin, process, when (YYYY-MM), rating /10 or null, timesBought, note?]
// Ratings are the combined score from the household tasting panel.

export type CoffeeEntry = [
  name: string,
  roaster: string,
  roast: string,
  origin: string,
  process: string,
  when: string,
  rating: number | null,
  times: number,
  note?: string,
]

export const COFFEES: CoffeeEntry[] = [
  ['Santa Lucia', 'Wild Ginger Coffee', 'Medium', 'Honduras', 'Washed', '2026-06', 6, 1],
  ['ACC Por La Pz', 'Receiver Coffee', 'Light', 'Colombia', 'Washed', '2026-06', 6, 1],
  ['Velvet', 'Velvet Sunrise', 'Medium', 'Brazil & Guatemala', 'Washed', '2026-06', 6, 1],
  ['Supernova', '94 Celcius', 'Dark', 'Costa Rica & Colombia', 'Washed & White Honey', '2026-06', null, 1],
  ['Bombe Duwancho', 'Traffic', 'Light', 'Ethiopia', 'Natural', '2026-06', 7, 1],
  ['Black Honey', 'Qielli', '', 'Indonesia', '', '2026-06', null, 1],
  ['Blue Mountain', 'Qielli', '', 'Indonesia', '', '2026-06', null, 1],
  ['Gayo Wine', 'Qielli', '', 'Indonesia', '', '2026-06', null, 1],
  ['Gayo', 'Qielli', '', 'Indonesia', '', '2026-06', 6, 1],
  ['Red Java', 'Qielli', '', 'Indonesia', '', '2026-06', 8, 1],
  ['Stiven', 'KOHI Micro-torréfacteur', 'Light-Medium', 'Colombia', 'Washed', '2026-05', 7, 1],
  ['Coast La Pastora', 'Modus Coffee Roastery', 'Medium', 'Costa Rica', 'Washed', '2026-05', 8, 1],
  ['Moonlight Blend', 'The Library', 'Dark', 'Brazil & Ethiopia', 'Natural', '2026-05', 6, 1],
  ['Ethiopia Yirgacheffe Edido', 'Hale', 'Light', 'Ethiopia', 'Washed', '2026-05', 8, 1],
  ['Nicaragua Matagalpa', 'Hale', 'Medium', 'Nicaragua', 'Washed', '2026-05', 7, 1],
  ['Rwenzori Station', 'Quietly Coffee', 'Medium-Light', 'Uganda', 'Natural', '2026-04', 8, 1],
  ['Antony Vasquez', 'Philo Coffee Co.', 'Medium-Light', 'Ethiopia', 'Washed', '2026-04', 6, 1],
  ['Ethiopia Washed', 'Hiyori Coffee', 'Light', 'Ethiopia', 'Washed', '2026-04', 7, 2],
  ['Ethiopia Bensa', 'Sam James', 'Light', 'Ethiopia', 'Washed', '2026-04', 7, 1],
  ['Rene', 'KOHI Micro-torréfacteur', 'Medium', 'Guatemala', 'Washed', '2026-03', 8, 1],
  ['Colosseo', 'Café Saint-Henri', 'Dark', 'Brazil', 'Natural', '2026-03', 7, 1],
  ['Irma Trochez', 'Subtext', 'Light', 'Honduras', 'Honey', '2026-03', 7, 1],
  ['Buncho', 'Subtext', 'Light', 'Ethiopia', 'Honey', '2026-03', 7, 1],
  ['Lica Torres', 'The Library', 'Medium', 'Costa Rica', 'Honey', '2026-03', 8, 1],
  ['Two Wheel', 'Rosso', 'Medium', 'Colombia & Brazil', 'Washed', '2026-02', 7, 1],
  ['Filipe Estela', 'Drumroaster Coffee', 'Light', 'Peru', 'Washed', '2026-02', 7, 1],
  ['Gentleman', 'De Mello', 'Medium-Dark', 'Brazil', 'Natural', '2026-02', 4, 3],
  ['Ethiopia Yirgacheffe (YirgZ)', 'Trebilcock', 'Medium', 'Ethiopia', 'Washed', '2025-12', 6, 1],
  ['Strawberry Washed Anaerobic', 'Brew En Route', 'Light', 'Colombia', 'Washed', '2025-12', 9, 1],
  ['Starlight', 'Hatch', 'Light', 'Seasonal blend', 'Washed', '2025-12', 8, 2],
  ['Finca Milan Melona', 'Hatch', 'Light', 'Colombia', 'Washed', '2025-12', 9, 1],
  ['Juan Jose Torres', 'Za & Klo', 'Medium-Light', 'Guatemala', 'Washed', '2025-12', 8, 1],
  ['Fernando Melgar', 'Receiver Coffee', 'Medium', 'Guatemala', 'Washed', '2025-12', 8, 1],
  ['Possibly Maybe', 'Quietly Coffee', 'Light', 'Papua New Guinea', 'Natural', '2025-12', 8, 1],
  ['Papua New Guinea Baroida Estate', 'Propeller', 'Light', 'Papua New Guinea', 'Washed', '2025-12', 7, 1],
  ['Lilac Dream: Gerba Dogo', 'Phil & Sebastian', 'Medium-Light', 'Ethiopia', 'Washed', '2025-12', 8, 1],
  ['Candy Floss #2', 'Escape Coffee', 'Medium-Light', 'El Salvador & Guatemala', 'Natural', '2025-12', 7, 1],
  ['Lagoinha', 'Epoch', 'Medium-Light', 'Brazil', 'Natural', '2025-12', 7, 1],
  ['Diever Galindez Pink Bourbon', 'Drumroaster Coffee', 'Medium-Light', 'Colombia', 'Washed', '2025-12', 8, 1],
  ['Yirgacheffe', 'Brulerie du Quai', 'Light', 'Ethiopia', 'Washed', '2025-12', 8, 1],
  ['Nicaraguan Las Segovias', 'Bean North', 'Dark', 'Nicaragua', 'Washed', '2025-12', 7, 1],
  ['Lychee Peachy', '94 Celcius', 'Light', 'Colombia', 'Washed', '2025-12', 9, 1],
  ['Figgy Pudding', 'Monogram Coffee', 'Light', 'Costa Rica & Ethiopia', 'Natural', '2025-12', 8, 1, 'Holiday blend'],
  ['Vara Blanca', 'Hale', 'Medium', 'Costa Rica', 'Red Honey', '2025-12', 7, 1],
  ['Korgua Estate AA', 'Velvet Sunrise', 'Dark', 'Papua New Guinea', 'Washed', '2025-11', 5, 1],
  ['Oh Fudge Yuki!', 'KOHI Micro-torréfacteur', 'Medium', 'Blend', 'Unknown', '2025-11', 7, 1],
  ["Jammin' Wid Chu", 'Holm Coffee', 'Light', 'Ethiopia & Peru', 'Natural & Washed', '2025-11', 7, 1],
  ['In The Sun', 'Quietly Coffee', 'Light-Medium', 'Guji, Ethiopia', 'Natural', '2025-09', 8, 1],
  ['Total Eclipse', 'Discovery Coffee', 'Dark', 'Colombia & Mexico', 'Washed', '2025-09', 4.5, 1],
  ['Hibi', 'De Mello', 'Medium', 'Brazil, Colombia & PNG', 'Natural & Washed', '2025-09', 6.5, 1],
  ['Finca Milan', 'Monogram Coffee', 'Light-Medium', 'Colombia', 'Nitro Natural', '2025-09', 9, 1],
  ['Banko Chelchele Supernatural', 'Monogram Coffee', 'Light-Medium', 'Ethiopia', 'Anaerobic Natural', '2025-09', 8, 1],
  ['Warmth Filter Blend', 'Monogram Coffee', 'Medium', 'Central & South America', 'Washed', '2025-09', 6.5, 1],
  ['Baseline', 'Ministry of Coffee', 'Medium-Dark', 'Blend', 'Washed', '2025-08', 5.5, 1],
  ['Brazil Natural', 'Ethica', 'Medium', 'Brazil', 'Natural', '2025-08', 6, 1],
  ['Naga Gesha', 'Coffee Wallas', 'Light', 'Panama', 'Washed', '2025-08', 8, 1],
  ['Wilton Benitez', 'Ethica', 'Light-Medium', 'Colombia', 'Experimental', '2025-08', 8, 1],
  ['Guatemala Waykan', 'Hale', 'Medium', 'Guatemala', 'Washed', '2025-08', 8, 1],
  ['Ethiopia Reji Kebele', 'Hale', 'Light', 'Ethiopia', 'Washed', '2025-08', 7.5, 1],
  ['Brazilian Yellow Bourbon WOC', 'Roasti', 'Medium', 'Brazil', 'Natural', '2025-07', 7, 1],
  ['Aponte Village Honey', 'Epoch', 'Medium', 'Colombia', 'Honey', '2025-07', 6, 1],
  ['Rwanda Dukunde Kawa', 'Agro', 'Light-Medium', 'Rwanda', 'Washed', '2025-07', 6.5, 1],
  ['Ethiopia Sidama Ardi', 'Trebilcock', 'Light', 'Ethiopia', 'Natural', '2025-07', 8, 1],
  ['Nicaragua El Volcan', 'Trebilcock', 'Medium', 'Nicaragua', 'Washed', '2025-07', 6.5, 1],
  ['La Fortuna', 'Trebilcock', 'Medium', 'Colombia', 'Washed', '2025-06', 8.5, 1, 'Early fermentation'],
  ['52', 'Buru Kudu', 'Medium-Dark', 'Blend', 'Mixed', '2025-06', 7.5, 1],
  ['El Paraiso 92', 'Hale', 'Light', 'Colombia', 'Anaerobic', '2025-06', 7.5, 1],
  ['El Borbollon', 'Hale', 'Medium', 'El Salvador', 'Washed', '2025-06', 7, 1],
  ['Ethiopia Sidama SOE', 'Rocanini Coffee', 'Light', 'Ethiopia', 'Washed', '2025-06', 8, 1],
  ['Brazil Natural SOE', 'Rocanini Coffee', 'Medium', 'Brazil', 'Natural', '2025-06', 7, 1],
  ['Danila Barbosa', 'Nordik Cafe', 'Medium', 'Brazil', 'Washed', '2025-06', 8.5, 1],
  ['Secret Sauce #5', 'Escape Coffee', 'Medium-Dark', 'Blend', 'Mixed', '2025-06', 9, 1],
  ['Base Camp Dark Roast', 'Counterpart Coffee', 'Dark', 'Blend', 'Washed', '2025-06', 6, 1],
  ['São Pedro', 'Hale', 'Medium', 'Brazil', 'Washed', '2025-04', 7.5, 1],
  ['Armenia', 'Hale', 'Medium', 'Colombia', 'Washed', '2025-04', 7.5, 1],
  ['Kawo Kamina', 'Hale', 'Light', 'Ethiopia', 'Washed', '2025-04', 7, 1],
  ['Community', 'Pilot', 'Medium', 'House blend', 'Mixed', '2025-04', 6, 1],
  ['Heritage', 'Pilot', 'Medium', 'House blend', 'Mixed', '2025-04', 4, 1],
  ['Honduras Moreno Family', 'Rogue Wave', 'Light-Medium', 'Honduras', 'Washed', '2025-04', 7.5, 1],
  ['Anhumas', 'Dispatch', 'Medium', 'Brazil', 'Washed', '2025-04', 6, 1],
  ['Shoondhisa', 'Manhattan', 'Light', 'Ethiopia', 'Washed', '2025-03', 6.5, 1],
  ['Kiwi Cola', 'Luna', 'Light', 'Experimental blend', 'Anaerobic', '2025-03', 7, 1],
  ['Los Guacharos', 'Luna', 'Light-Medium', 'Colombia', 'Washed', '2025-03', 6.5, 1],
  ['Idefonso Córdoba ~ Aji', 'Luna', 'Light', 'Colombia', 'Experimental', '2025-03', 5, 1],
  ['Ethiopia Nguisse Nare Murago', 'Rogue Wave', 'Light', 'Ethiopia', 'Washed', '2025-02', 8, 1],
  ['Colombia Las Cascadas', 'Rogue Wave', 'Medium', 'Colombia', 'Washed', '2025-02', 7.5, 1],
  ['Guatemala Ella Todos Santos', 'Rogue Wave', 'Medium', 'Guatemala', 'Washed', '2025-02', 6.5, 1],
  ['Ethiopia Bensa', 'De Mello', 'Light', 'Ethiopia', 'Washed', '2025-01', 8.5, 4, 'The house beans'],
  ['Ethiopia Habtamu F. Aga', 'De Mello', 'Light', 'Ethiopia', 'Washed', '2025-01', 7, 1],
  ['Mystic Melon', 'Phil & Sebastian', 'Light', 'Seasonal blend', 'Experimental', '2025-01', 7, 1],
  ['Saison', 'Cafe Pista', 'Light', 'Seasonal blend', 'Washed', '2025-01', 7, 1],
  ['Miguel Rodriguez', 'Cafe Pista', 'Light', 'Colombia', 'Washed', '2025-01', 7, 1],
  ['Espirito Santo', 'Cafe Pista', 'Medium', 'Brazil', 'Washed', '2025-01', 4.5, 1],
  ['Silvia Ordonez', 'Dispatch', 'Light-Medium', 'Honduras', 'Washed', '2024-12', 6.5, 1],
  ['The Mad House Roast', 'Angry Roaster', 'Medium-Dark', 'Colombia', 'Washed', '2024-12', 6.5, 1],
  ['Nicaragua', 'Angry Roaster', 'Medium', 'Nicaragua', 'Washed', '2024-12', 6.5, 1],
  ['Ethiopia', 'Angry Roaster', 'Light', 'Ethiopia', 'Washed', '2024-12', 6.5, 1],
  ['Ethiopia Nguisse Nare Bombe', 'Rogue Wave', 'Light', 'Ethiopia', 'Washed', '2024-12', 7, 1],
  ['Eldorado de Brazil', 'Nucleus', 'Medium', 'Brazil', 'Natural', '2024-12', 6, 1],
  ['La Bendicion', 'Cafe Pista', 'Medium', 'Guatemala', 'Washed', '2024-10', 8.5, 1],
  ['So', 'Cafe Pista', 'Medium', 'House blend', 'Mixed', '2024-10', 8, 1],
  ['Bookkisa Natural', 'Cafe Pista', 'Light', 'Ethiopia', 'Natural', '2024-10', 7.5, 1],
  ['Blend Classique', 'Dispatch', 'Medium-Dark', 'Blend', 'Washed', '2024-10', 8, 1],
  ['Serra Dos Ciganos', 'Dispatch', 'Medium', 'Brazil', 'Washed', '2024-10', 7.5, 1],
  ['Bulambuli Lavé', 'Dispatch', 'Light', 'Uganda', 'Washed', '2024-10', 6, 1],
  ['Brazilian Yellow Bourbon', 'Roasti', 'Medium', 'Brazil', 'Natural', '2024-10', 7, 1],
  ['Diablo', 'Omnia', 'Dark', 'El Salvador', 'Washed', '2024-10', 6.5, 1],
  ['Supernova', 'Hatch', 'Light', 'Seasonal blend', 'Anaerobic blend', '2024-09', 7.5, 1],
  ['El Paraiso Lychee Castillo', 'Hatch', 'Light', 'Colombia', 'Lychee anaerobic', '2024-09', 8.5, 1],
  ["People's Daily", 'Social', 'Medium', 'House blend', 'Mixed', '2024-09', 7.5, 1],
  ['Yirgacheffe Ethiopia', 'Social', 'Light', 'Ethiopia', 'Washed', '2024-09', 6.5, 1],
  ['Volcan Azul Gesha', 'Social', 'Light', 'Costa Rica', 'Washed', '2024-09', 6.5, 1],
  ['Tariku Kare', 'Java', 'Light', 'Ethiopia', 'Washed', '2024-08', 7.5, 1],
  ['Francisco Garcia', 'Java', 'Medium', 'Colombia', 'Washed', '2024-08', 7, 1],
  ['Madre Maria', 'Java', 'Medium', 'Colombia', 'Washed', '2024-08', 6, 1],
  ['Blue Jeans', 'Rosso', 'Medium', 'Indonesia', 'Washed', '2024-08', 7, 1],
  ['Ruiru AA', 'Hatch', 'Light', 'Kenya', 'Washed', '2024-07', 7.5, 1],
  ['Concepcion Buena Vista', 'Hatch', 'Medium', 'Guatemala', 'Washed', '2024-07', 6.5, 1],
  ['Starry Path', 'Seven Mystery', 'Light', 'Experimental blend', 'Anaerobic', '2024-07', 5, 1],
  ['Blackberry Jam Decaf', 'September', 'Medium', 'Colombia', 'Washed decaf', '2024-07', 7, 1],
  ['Amparo Botina', 'September', 'Light', 'Colombia', 'Washed', '2024-07', 8, 1],
  ['Erick Bravo', 'September', 'Light', 'Colombia', 'Washed', '2024-07', 7.5, 1],
  ['Diego Bermudez', 'September', 'Light', 'Colombia', 'Thermal shock', '2024-07', 6.5, 2, 'Espresso'],
  ['Finca Cerro Azul', 'Hatch', 'Light', 'Colombia', 'Natural', '2024-06', 8, 1],
  ['Golden Hour', 'De Mello', 'Medium', 'Blend', 'Washed', '2024-06', 7, 2],
  ['Café Magique', 'De Mello', 'Medium', 'Blend', 'Washed', '2024-06', 6, 2],
  ['Bottle Neck', 'Detour', 'Medium', 'Blend', 'Washed', '2024-05', 6.5, 1],
  ['Punch Buggy', 'Detour', 'Medium', 'Blend', 'Washed', '2024-05', 5, 1, 'Espresso'],
  ['Bouncy Castle', 'Detour', 'Light', 'Blend', 'Washed', '2024-05', 5, 1],
  ['Muzo Ikizere', 'Dispatch', 'Light', 'Rwanda', 'Washed', '2024-05', 7, 1],
  ['Dancing Goats', 'De Mello', 'Medium', 'Blend', 'Washed', '2024-04', 6.5, 1],
  ['Birthday Cake', 'De Mello', 'Light', 'Seasonal blend', 'Infused', '2024-04', 6.5, 1, 'Limited time'],
  ['Colombia Buesaco Pequeños', 'Subtext', 'Medium', 'Colombia', 'Washed', '2024-04', 7, 1, 'Espresso'],
  ['Colombia Adriana Franco', 'Subtext', 'Light', 'Colombia', 'Washed', '2024-04', 6.5, 1],
  ['Colombia Ernedis Rodriguez', 'Subtext', 'Light', 'Colombia', 'Washed', '2024-04', 6, 1],
  ['Buttercream: Diego Bermudez', 'September', 'Light', 'Colombia', 'Thermal shock', '2024-03', 7, 1],
  ['Daterra Milk Espresso', 'September', 'Medium', 'Brazil', 'Pulped natural', '2024-03', null, 1],
  ['Janja Hill', 'September', 'Medium', 'Colombia', 'Washed', '2024-03', null, 1],
  ['Esnaider Ortega', 'September', 'Light', 'Colombia', 'Washed', '2024-03', null, 1],
  ['Zumachi Decaf', 'De Mello', 'Medium', 'Colombia', 'Washed decaf', '2024-02', 7, 1],
  ['Costa Rica Arleen & Maria', 'De Mello', 'Light', 'Costa Rica', 'Washed', '2024-02', null, 1],
  ['Irineo Ramirze', 'September', 'Light', 'Colombia', 'Washed', '2024-02', null, 1],
  ['Los Patios Solsticio', 'September', 'Light', 'Colombia', 'Anaerobic', '2024-02', null, 1],
  ['Percy Pintado', 'September', 'Light', 'Peru', 'Washed', '2024-02', null, 1],
  ['Daterra Blossom', 'September', 'Medium', 'Brazil', 'Pulped natural', '2024-01', null, 1],
  ['Githembe AA', 'September', 'Light', 'Kenya', 'Washed', '2024-01', null, 1],
  ['Guatemala Ella Todos Santos', 'De Mello', 'Medium', 'Guatemala', 'Washed', '2024-01', null, 1],
]

// Roasters queued up but not yet logged.
export const WISHLIST = [
  'Subtext',
  'Rabbit Hole Roasters',
  'Phil & Sebastian',
  'Coffee Island',
  'Black Sheep',
  '49th Parallel',
]
